name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  CI_CD:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.4.0
      - name: Install Node
        uses: actions/setup-node@v3.6.0
      - name: Install Packages
        run: npm ci --no-audit
      - name: Test
        run: npm run coverage
      - name: Report coverage
        uses: codecov/codecov-action@v3.1.1
        with:
          fail_ci_if_error: true
